export { Cart } from './cart'
export { Category } from './category'
export { Header } from './header'
export { Hero } from './hero'
export { Personalization } from './personalization'
export { Products } from './products'
export { Promo } from './promo'
export { Specs } from './specs'
